# Generated by Django 5.1.2 on 2024-11-01 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name="Nom de l'équipe")),
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False, unique=True, verbose_name='Slug')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='events.event')),
            ],
        ),
    ]
