# Generated by Django 5.1.2 on 2024-10-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, primary_key=True, serialize=False, unique=True, verbose_name='Slug'),
        ),
    ]
