# Generated by Django 5.1.2 on 2024-10-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField(verbose_name='date')),
                ('event_location', models.CharField(max_length=200)),
                ('event_description', models.CharField(max_length=200)),
                ('event_image', models.CharField(max_length=200)),
                ('event_start_time', models.DateTimeField(verbose_name='start time')),
                ('event_end_time', models.DateTimeField(verbose_name='end time')),
            ],
        ),
    ]
