# Generated by Django 5.1.2 on 2024-10-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_outdoor',
            field=models.BooleanField(default=False, verbose_name='outdoor ?'),
        ),
    ]
