# Generated by Django 5.1.2 on 2024-10-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du tournoi')),
                ('players', models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (6, 6)], default=3, verbose_name='Nombre de joueurs par équipe')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('city', models.CharField(max_length=200, verbose_name='Ville')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lieu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Image')),
                ('mode', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], default='indoor', max_length=10, verbose_name='Indoor/Outdoor')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
            ],
        ),
    ]
