# Generated by Django 5.1.2 on 2024-11-01 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, default='Gournay / Marne', max_length=200, unique=True, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 7, 7, 0, 0), unique=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), unique=True, verbose_name='Heure de fin'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default='Mairie', max_length=200, null=True, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, default='Green Volley', max_length=200, unique=True, verbose_name='Nom du tournoi'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), unique=True, verbose_name='Heure de début'),
        ),
    ]
