# Generated by Django 5.1.2 on 2024-10-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_event_date_event_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='outdoor',
        ),
        migrations.AddField(
            model_name='event',
            name='mode',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], default='indoor', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='players',
            field=models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (6, 6)], default=3),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Image'),
        ),
    ]
