# Generated by Django 5.1.2 on 2024-11-01 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=50, verbose_name='Nom')),
                ('firstname', models.CharField(max_length=50, verbose_name='Prénom')),
                ('sex', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=2, verbose_name='Sexe')),
                ('birthday', models.DateField(blank=True, unique=True, verbose_name='Date')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='teams.team')),
            ],
        ),
    ]
